class MainLocators:
    LEARN_MORE = '//*[text()="Learn more"]'
    SEARCH_ICON = '//*[@id="fe-nav-search-btn"]'
    SEARCH_INPUT = '//*[@id="fe-search-box"]'
    PRODUCT_NAME = '//*[@class="solutionWrapper"]//a'
    SUBMIT = '//*[@type="submit"]'
    SOLUTION_WRAPPER = '//*[@class="solutionWrapper"]'
    PRODUCT_OVERVIEW = '//div[@class="col-sm-5 computer-screen"]'
    # FRED_MESSAGE = '//*[contains(@aria-label, "Chat message")]'
    FRED_MESSAGE = '//*[contains(text(), "For quality assurance")]'
    # FRED_ICON = '//*[contains(@class,"drift-widget-avatar square")]'
    FRED_ICON = '//*[@id="root"]/main/div[3]/div[1]/div[1]/div/div'
    CHAT_BOT = '//header[@class="drift-widget-header"]'
